export const siteConfig = {
  name: 'MaxLiving Chiropractic - New Braunfels',
  shortName: 'MaxLiving New Braunfels',
  phone: '(830) 255-4350',
  phoneTel: '8302554350',
  address: {
    street: '741 Generations Dr, Suite 200',
    city: 'New Braunfels',
    state: 'TX',
    zip: '78130',
    full: '741 Generations Dr, Suite 200, New Braunfels, TX 78130',
  },
  emails: {
    rachel: 'dr.rachel@maxlivingnewbraunfels.com',
    info: 'info@maxlivingnewbraunfels.com',
  },
  hours: {
    mon: '7:45\u201310:30 AM, 3\u20136 PM',
    tue: '7:45\u201310:30 AM',
    wed: '7:45\u201310:30 AM, 3\u20136 PM',
    thu: '7:45\u201310:30 AM, 3\u20136 PM',
    fri: 'Closed',
    sat: 'Closed',
    sun: 'Closed',
  },
  serviceAreas: ['New Braunfels', 'San Marcos', 'Seguin', 'Canyon Lake', 'Kyle', 'Wimberley'],
  googleRating: 5.0,
  googleReviews: 67,
  franchise: 'MaxLiving Health Center',
  tagline: 'Inspiring people to honor the wisdom of the body and live a life free from interference.',
  doctors: {
    rachel: {
      name: 'Dr. Rachel Diestel, D.C.',
      shortName: 'Dr. Rachel',
      education: 'Parker University',
      certifications: ['Advanced Spinal Correction', 'Nutrition', 'Exercise', 'Detoxification', 'Pre- and Peri-natal Techniques'],
      specialties: ['Prenatal Care', 'Pediatric Care', 'Nutrition', 'Detox'],
      email: 'dr.rachel@maxlivingnewbraunfels.com',
    },
    travis: {
      name: 'Dr. Travis Diestel, D.C.',
      shortName: 'Dr. Travis',
      education: 'Parker University',
      certifications: ['Advanced Spinal Correction', 'Level 2 Activator', 'Nutrition', 'Exercise', 'Detoxification'],
      specialties: ['Corrective Exercise', 'Military/First Responder', 'Spinal Correction', 'Activator'],
      email: 'info@maxlivingnewbraunfels.com',
    },
  },
  services: [
    { name: 'Chiropractic Adjustments', slug: 'spinal-correction-new-braunfels', href: '/spinal-correction-new-braunfels' },
    { name: 'Prenatal Chiropractic', slug: 'prenatal-chiropractic-care-new-braunfels', href: '/prenatal-chiropractic-care-new-braunfels' },
    { name: 'Pediatric Chiropractic', slug: 'pediatric-chiropractic-care-new-braunfels', href: '/pediatric-chiropractic-care-new-braunfels' },
    { name: 'Corrective Exercises', slug: 'corrective-exercises-new-braunfels', href: '/corrective-exercises-new-braunfels' },
    { name: 'Nutritional Coaching', slug: 'nutritional-coaching-new-braunfels', href: '/nutritional-coaching-new-braunfels' },
    { name: 'Massage Therapy', slug: 'massage-therapy-new-braunfels', href: '/massage-therapy-new-braunfels' },
    { name: 'Detoxification', slug: 'detoxification-programs-new-braunfels', href: '/detoxification-programs-new-braunfels' },
  ],
  conditions: [
    { name: 'Back Pain', slug: 'back-pain-treatment-new-braunfels', href: '/back-pain-treatment-new-braunfels' },
    { name: 'Neck Pain', slug: 'neck-pain-treatment-new-braunfels', href: '/neck-pain-treatment-new-braunfels' },
    { name: 'Sciatica', slug: 'sciatica-treatment-new-braunfels', href: '/sciatica-treatment-new-braunfels' },
    { name: 'Headaches & Migraines', slug: 'headache-treatment-new-braunfels', href: '/headache-treatment-new-braunfels' },
  ],
}
