export const siteConfig = {
  name: 'MaxLiving Chiropractic - New Braunfels',
  shortName: 'MaxLiving New Braunfels',
  phone: '(830) 255-4350',
  phoneTel: '8302554350',
  address: {
    street: '741 Generations Dr, Suite 200',
    city: 'New Braunfels',
    state: 'TX',
    zip: '78130',
    full: '741 Generations Dr, Suite 200, New Braunfels, TX 78130',
  },
  emails: {
    rachel: 'dr.rachel@maxlivingnewbraunfels.com',
    info: 'info@maxlivingnewbraunfels.com',
  },
  hours: {
    mon: '7:45\u201310:30 AM, 3\u20136 PM',
    tue: '7:45\u201310:30 AM',
    wed: '7:45\u201310:30 AM, 3\u20136 PM',
    thu: '7:45\u201310:30 AM, 3\u20136 PM',
    fri: 'Closed',
    sat: 'Closed',
    sun: 'Closed',
  },
  serviceAreas: ['New Braunfels', 'San Marcos', 'Seguin', 'Canyon Lake', 'Kyle', 'Wimberley'],
  googleRating: 5.0,
  googleReviews: 67,
  franchise: 'MaxLiving Health Center',
  tagline: 'The best doctor lives inside of you -- we just remove the interference and let your body do what it\'s designed to do.',
  doctors: {
    rachel: {
      name: 'Dr. Rachel Diestel, D.C.',
      shortName: 'Dr. Rachel',
      education: 'Parker University',
      certifications: ['Advanced Spinal Correction', 'Nutrition', 'Exercise', 'Detoxification', 'Pre- and Peri-natal Techniques'],
      specialties: ['Structural Correction', 'Prenatal Care', 'Pediatric Care', 'Nutrition', 'Detox'],
      email: 'dr.rachel@maxlivingnewbraunfels.com',
    },
    travis: {
      name: 'Dr. Travis Diestel, D.C.',
      shortName: 'Dr. Travis',
      education: 'Parker University',
      certifications: ['Advanced Spinal Correction', 'Level 2 Activator', 'Nutrition', 'Exercise', 'Detoxification'],
      specialties: ['Structural Correction', 'Prenatal Care', 'Pediatric Care', 'Corrective Exercise', 'Activator'],
      email: 'info@maxlivingnewbraunfels.com',
    },
  },
  services: [
    { name: 'Chiropractic Adjustments', slug: 'spinal-correction-new-braunfels', href: '/spinal-correction-new-braunfels' },
    { name: 'Prenatal Chiropractic', slug: 'prenatal-chiropractic-care-new-braunfels', href: '/prenatal-chiropractic-care-new-braunfels' },
    { name: 'Pediatric Chiropractic', slug: 'pediatric-chiropractic-care-new-braunfels', href: '/pediatric-chiropractic-care-new-braunfels' },
    { name: 'Corrective Exercises', slug: 'corrective-exercises-new-braunfels', href: '/corrective-exercises-new-braunfels' },
    { name: 'Nutritional Coaching', slug: 'nutritional-coaching-new-braunfels', href: '/nutritional-coaching-new-braunfels' },
    { name: 'Detoxification', slug: 'detoxification-programs-new-braunfels', href: '/detoxification-programs-new-braunfels' },
  ],
  conditions: [
    { name: 'Back Pain', slug: 'back-pain-relief-new-braunfels', href: '/back-pain-relief-new-braunfels' },
    { name: 'Neck Pain', slug: 'neck-pain-relief-new-braunfels', href: '/neck-pain-relief-new-braunfels' },
    { name: 'Sciatica', slug: 'sciatica-care-new-braunfels', href: '/sciatica-care-new-braunfels' },
    { name: 'Headaches & Migraines', slug: 'headache-relief-new-braunfels', href: '/headache-relief-new-braunfels' },
  ],
}
